### ISSUE TITLE
What is the import order of SQL files on the sample-data directory ?

### ISSUE THREAD

**Issue by julianomaciel** [MLocks83/real-estate-database#1]
@MLocks83 
Could you please supply instructions on the importing order of the sample data you provide ?
I see a lot of relationships and dependencies on the ER model but, if you specify it in the files, it will be easier.

Thank you for sharing this database project!

Best regards,
Juliano.

**Comment by MLocks83** [comment]
@julianomaciel,
I have already updated the issue and placed the order of insertion of the tables.
Thanks for the tip.
