### ISSUE TITLE
Personal attributes duplication on tables guarantor, tenant, owner and spouse.

### ISSUE THREAD

**Issue by julianomaciel** [MLocks83/real-estate-database#3]
@MLocks83 
The tables 'guarantor', 'tenant', 'owner' and 'spouse'  share the same personal information (e.g, name, rg, birthday, archived date, etc.). 
IMHO, you can centralize this in a table, named like 'personal_info', and use the 1:1 relationship, avoiding this data redundancy.

Best regards,
Juliano.

**Comment by MLocks83** [comment]
Hi @julianomaciel ,

Thanks for the feedback.
I just modified the tables to remove data redundancy, as you mentioned.

Here's the image of the new modeling.

![screenshot from 2018-03-09 13-28-51](https://user-images.githubusercontent.com/35237132/37218092-382110b8-239e-11e8-8f1e-7da9354e584b.png)


Thankful,
Martha.

**Comment by julianomaciel** [comment]
@MLocks83 
You got right to the point. I think now is much better.
But, the tables 'tenant' and 'owner' are equal, and I don't think using a flag in a single table to differentiate one of another will become more intuitive... In fact, if in the future you add more fields, could happen that you have to separate again.

Thank you for the improvement.

Best regards,
Juliano.
