### ISSUE TITLE
All insert into SQL instruction have database name - why not write 'USE' statement one time only?

### ISSUE THREAD

**Issue by julianomaciel** [MLocks83/real-estate-database#4]
@MLocks83 
When running one of the SQL files you provide in 'sample-data' directory, I noticed you put all instructions with database name.
Doing this way we cannot have other databases with different names importing this files, or we have to rename or remove it from all instructions from the files.
IMHO, it should write the USE database statement and let the "insert into's" without it.

Best regards,
Juliano.

**Comment by MLocks83** [comment]
@julianomaciel, 

Thank you for the advice.
I implemented this change in the commit [d8858307eb818a12f437f41daedf740127fb4480](https://github.com/MLocks83/real-estate-database/commit/d8858307eb818a12f437f41daedf740127fb4480)

Best regards, Martha.
